sudo: required
language: node_js
node_js:
  - '11'
script:
  - env
  - yarn
  - yarn pack
  - ls -l ./bin
  - ./bin/run compare \
    --gitRepository='https://github.com/ramda/ramda.git' \
    --installScript='yarn' \
    --buildScript='yarn build:es' \
    --currentBranch='CrossEye-patch-1' \
    --distPath='es' \
    --targetBranch='master'
